name: Validate and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Use the Python version of your choice

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure you have a requirements.txt file for dependencies

    - name: Run validations
      run: |
        python validation.py  # Adjust based on your validation script

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q
